### ISSUE TITLE
Problems building usb with crostini.

### ISSUE THREAD

**Issue by Metal-Toilet** [eupnea-linux/eupnea#17]
I'm having different issues when building with crostini. (still in the crosh/shell part) 
```shell
crosh> shell
chronos@localhost / $ vmc stop termina
chronos@localhost / $ vmc start termina
(termina) chronos@localhost ~ $ vmc container termina penguin --privileged true
-bash: vmc: command not found
```
I thought this might be where I was putting the command so I then opened a new bash session in a new tab:
```shell
crosh> shell
chronos@localhost / $ vmc container termina penguin --privileged true
ERROR vsh: [vsh.cc(150)] Failed to launch vshd for termina:penguin: requested container does not exist: penguin
```
Any ideas? Was I putting commands in the right place? All help is appriciated.

(cross posted to the discord server)

**Comment by Metal-Toilet** [comment]
I did as you instructed over discord and tried to run the script without any commands in crosh. Here is the output.
```shell
h@penguin:~$ git clone --depth=1 https://github.com/eupnea-linux/eupnea; cd eupnea; ./main.py
Cloning into 'eupnea'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 55 (delta 8), reused 23 (delta 1), pack-reused 0
Receiving objects: 100% (55/55), 40.73 KiB | 2.71 MiB/s, done.
Resolving deltas: 100% (8/8), done.
Python 3.10 or higher is required. Attempt to install? (Y/n)
Y
Switching to unstable channel
Installing python 3.10
debconf: delaying package configuration, since apt-utils is not installed
Python 3.10 installed
Please restart the script with: "./main.py"
h@penguin:~/eupnea$ ./main.py
Welcome to Eupnea
This script will create a bootable Eupnea USB Stick/SD-card
Please answer the following questions.
(If you dont know what to answer, just press enter and the recommended answer will be used)
Which Linux distro(flavor) would you like to use?
Available options: Ubuntu(default, recommended), Debian, Arch, Fedora
Debian  
Debian stable selected
Which desktop environment(interface) would you like to use?
Available options: Gnome(default, recommended), KDE(recommended), MATE, Xfce(recommended for weak devices), LXQt(recommended for weak devices), budgie, cli
Gnome
Gnome selected
Enter username to be used in Eupnea
Username(default: 'localuser'): henry
Please set a secure password
Password: 
Repeat password: 
Password set
Enter hostname for the chromebook.(Hostname is something like a device name)
Hostname(default: 'eupnea-chromebook'): de-chrome-book          
Would you like to rebind the Search/Super/Win key to Caps Lock?(NOT RECOMMENDED)
Type yes to rebind. Press enter to keep old binding

Search key will be Super/Win key
No available USBs/SD-cards found. Building image file.

User input complete
Traceback (most recent call last):
  File "/home/h/eupnea/./main.py", line 102, in <module>
    main_pid=os.getpid(), user_id=user_id, build_options=user_input.user_input())
  File "/home/h/eupnea/user_input.py", line 245, in user_input
    create_iso
UnboundLocalError: local variable 'create_iso' referenced before assignment
h@penguin:~/eupnea$ 
```

**Comment by Apacelus** [comment]
It seems that its impossible to build eupnea from crostini, as losetup wont work in it. I will try and add support for building on chromeos directly
