### ISSUE TITLE
Failure installing Arch Gnome

### ISSUE THREAD

**Issue by CorruptedPlazma** [eupnea-linux/eupnea#21]
```
(venv) (bullseye)inderix@localhost:~$ git clone --depth=1 https://github.com/eupnea-linux/eupnea; cd eupnea; ./main.py
Cloning into 'eupnea'...
remote: Enumerating objects: 55, done.
remote: Counting objects: 100% (55/55), done.
remote: Compressing objects: 100% (50/50), done.
remote: Total 55 (delta 9), reused 21 (delta 1), pack-reused 0
Receiving objects: 100% (55/55), 41.29 KiB | 13.76 MiB/s, done.
Resolving deltas: 100% (9/9), done.
Welcome to Eupnea
This script will create a bootable Eupnea USB-drive/SD-card/image for you.
You will now be asked a few questions. If you dont know what to answer, just press 'enter' and the recommended answer will be used.
(Press enter to continue)
Which Linux distro(flavor) would you like to use?
Available options: Ubuntu(default, recommended), Debian, Arch, Fedora
Arch
Arch selected
Which desktop environment(Desktop GUI) would you like to use?
Available options: Gnome(default, recommended), KDE(recommended), MATE, Xfce(recommended for weak devices), LXQt(recommended for weak devices), deepin, budgie, cli

Gnome selected
Enter username to be used in Eupnea
Username(default: 'localuser'): inderix
Using inderix as username
Please set a secure password
Password: 
Repeat password: 
Password set
Enter hostname for the chromebook.(Hostname is something like a device name)
Hostname(default: 'eupnea-chromebook'): archbook
Using archbook as hostname
Would you like to rebind the Search/Super/Win key to Caps Lock?(NOT RECOMMENDED)
Type yes to rebind. Press enter to keep old binding: 
Search key will be Super/Win key
sda           OneTouch_HDD 931.5G 
Enter USB-drive/SD-card name(example: sdb) or "image" to build an image
image
Building image instead of writing directly
User input complete
Starting build
Preparing host system
Failed to unmount /tmp/eupnea-build/fedora-tmp-mnt, ignore
Cleaning + preparing host system
Failed to remove /tmp/eupnea-build with python, using bash
Creating mount points
Installing vboot and cgpt packages
Packages already installed
Downloading stable 5.10 kernel
.........................Kernel files downloaded successfully
Downloading latest arch rootfs
Downloaded: 167mb
Downloading firmware
.Cloning into '/tmp/eupnea-build/firmware'...
remote: Finding sources: 100% (1415/1415)
remote: Total 1415 (delta 355), reused 1152 (delta 355)
Receiving objects: 100% (1415/1415), 92.32 MiB | 530.00 KiB/s, done.
Resolving deltas: 100% (355/355), done.
Updating files: 100% (1418/1418), done.
Preparing image
Mounting empty image
Preparing device/image
Flashing kernel to device/image
32584+0 records in
32584+0 records out
16683008 bytes (17 MB, 16 MiB) copied, 0.16087 s, 104 MB/s
Creating rootfs part
mke2fs 1.46.2 (28-Feb-2021)
Device/image preparation complete
Extracting rootfs
Extracting arch rootfs
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.xattr.security.capability'
..
Rootfs extraction complete
Applying distro agnostic configuration
No such file or directory: /mnt/eupnea/lib/modules, ignoring

Extracting kernel headers
Configuring user
Configuring Arch
Traceback (most recent call last):
  File "/home/inderix/eupnea/./main.py", line 108, in <module>
    build = build.start_build(verbose, local_path=args.local_path, kernel_type=kernel_type, dev_release=dev_release,
  File "/home/inderix/eupnea/build.py", line 456, in start_build
    distro.config(build_options["de_name"], build_options["distro_version"], root_partuuid, verbose)
  File "/home/inderix/eupnea/distro/arch.py", line 9, in config
    chroot("systemctl enable NetworkManager.service")
  File "/home/inderix/eupnea/distro/arch.py", line 120, in chroot
    bash(f'arch-chroot /mnt/eupnea bash -c "{command}" 2>/dev/null 1>/dev/null')  # supress all output
  File "/home/inderix/eupnea/functions.py", line 115, in bash
    output = subprocess.check_output(command, shell=True, text=True).strip()
  File "/usr/local/lib/python3.10/subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/local/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'arch-chroot /mnt/eupnea bash -c "systemctl enable NetworkManager.service" 2>/dev/null 1>/dev/null' returned non-zero exit status 1.
```

Using a Python 3.10 Venv, ChromeOS 105.0.5195.134, Crouton Chroot (Debian Bullseye)

**Comment by Apacelus** [comment]
Already fixed in https://github.com/eupnea-linux/eupnea/commit/e9a8a42735ea3c8bf7c7c3533a7c92d8c43b2aee
